version: "3"
services:
  db:
    container_name: db
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    ports:
      - 3306:3306
    
  webapp:
    container_name: webapp
    build:
      context: . 
      dockerfile: ./docker/webapp/Dockerfile
    command: npm start
    depends_on: 
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
