version: "3"
services:
  webapp:
    build:
      context: . 
      dockerfile: ./docker/webapp/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
  db:
    build: ./docker/db
    ports:
      - 3306:3306