version: "3"
services:
  webapp:
    container_name: webapp
    build:
      context: . 
      dockerfile: ./docker/webapp/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
  db:
    container_name: db
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    